universe                = docker
docker_image            = yashsarrof/formal-language-suite:torch2100-cu128-v4

environment             = "USER=condor; HOME=/tmp; TORCHINDUCTOR_CACHE_DIR=/tmp/torch_inductor; WANDB_ENTITY={YOUR NAME} WANDB_PROJECT={PROJECT NAME} WANDB_API_KEY={YOUR API KEY}"


run_id = $(ClusterId).$(ProcId)
model = transformer/olmo_nope

# Executable + arguments
executable              = execute.sh
arguments = algorithmic/language_modeling_train.py --model $(model) --task $(task) --job-id $(run_id) --logging-steps 100 --eval-steps 100

# Logging
output                  = /scratch/{PATH TO FOLDER}.out
error                   = /scratch/{PATH TO FOLDER}.err
log                     = /scratch/{PATH TO FOLDER}.log

# File transfer
should_transfer_files   = YES
when_to_transfer_output = ON_EXIT

# Resources
request_GPUs            = 1
request_CPUs            = 1
request_memory          = 4G

# Constraints
requirements            = UidDomain == "cs.uni-saarland.de"
gpus_minimum_capability = 7.0
+WantGPUHomeMounted     = true
+WantScratchMounted     = true

queue task in (
    addition
    multiplication
    bin_majority_interleave
    bin_majority
    flipflop
    majority
    mkar
    mqar
    repeat_copy
    selective_copy
    sort
    unique_copy
)
