universe                = docker
docker_image            = yashsarrof/formal-language-suite:torch2100-cu128-v4

environment             = "USER=condor; HOME=/tmp; TORCHINDUCTOR_CACHE_DIR=/tmp/torch_inductor; WANDB_ENTITY=kandra WANDB_PROJECT=HybridLengthGeneralization WANDB_API_KEY=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"

run_id = $(ClusterId)_tasks
# Executable + arguments
executable              = execute.sh
arguments               = algorithmic/run_scripts/language_modeling_train_ssm.py --task $(task) --job-id $(run_id) --logging-steps 100 --eval-steps 100 --use-olmo

# Logging
output                  = /scratch/{desired path}
error                   = /scratch/{desired path}
log                     = /scratch/{desired path}

# File transfer
should_transfer_files   = YES
when_to_transfer_output = ON_EXIT

# Resources
request_GPUs            = 1
request_CPUs            = 1
request_memory          = 2G

# Constraints
requirements            = UidDomain == "cs.uni-saarland.de"
+WantGPUHomeMounted     = true
+WantScratchMounted     = true

queue task in (
    addition
    bin_majority_interleave
    bin_majority
    majority
    flipflop
    mkar
    mqar
    parity
    repeat_copy
    selective_copy
    sort
    unique_copy    
)
